### ISSUE TITLE
TypeError: this.listenMouseFunc is not a function at PopoverContent.ngOnDestroy

### ISSUE THREAD

**Issue by daggerok** [pleerock/ng2-popover#50]
hello,
after update ng2-popover up to 0.0.14, subject exception is appears for next component with popover:

```html
<div *ngIf="!removed">
  <a class="list-group-item">
    {{ project?.name }}
    <span [popover]="projectPopover"
          [popoverAnimation]="true"
          [popoverCloseOnMouseOutside]="true"
          class="glyphicon glyphicon-remove"></span>

    <popover-content #projectPopover
                     title="Are you sure?"
                     placement="right"
                     [animation]="true"
                     [closeOnClickOutside]="true">

      <form (ngSubmit)="onProjectDelete(project); removed = true"
            class="form-group">

        <label for="confirm">Please type project name to confirm</label>

        <div class="input-group">
          <input id="confirm"
                 name="confirm"
                 class="form-control"
                 #confirm="ngModel"
                 [(ngModel)]="confirm.confirm"
                 type="text" required/>

          <span class="input-group-btn">
            <button type="submit"
                    class="btn btn-default"
                    [disabled]="!isProjectName(confirm.value)"
                    [ngClass]="{'btn-danger': isProjectName(confirm.value)}">
              <span *ngIf="isProjectName(confirm.value)">Go!</span>
              <span class="text-muted"
                    *ngIf="!isProjectName(confirm.value)">N/A</span>
            </button>
          </span>
        </div>
      </form>
    </popover-content>
  </a>
</div>
```

I'm using: 
```json
"@angular/*": "2.4.3", 
"ng2-popover": "0.0.14",
"typescript": "2.1.5",
"angular2-template-loader": "0.6.0",
"awesome-typescript-loader": "3.0.0-beta.18",
```

**Comment by PickleyD** [comment]
`[popoverCloseOnMouseOutside]="true"` - will close the popover when mouse hovers outside of popover

`[closeOnClickOutside]="true"` - will close popover only when mouse clicks outside of popover

Do you still get the error if you use only **one** of these?

Even so, I guess some existence checks should be put on ngOnDestroy to prevent this from happening.

**Comment by daggerok** [comment]
Thank you for response,
error is missing if Iusing only on attribute (in my case I removed `[popoverCloseOnMouseOutside]="true"` from span
seems like when item is removing from page, it's binding tries call popoverCloseOnMouseOutside handler  which is not exists anymore.

ok, this is enough for now
thanks for your help
